### ISSUE TITLE
"api" Routing

### ISSUE THREAD

**Issue by vorcigernix** [beyonk-adventures/now-sapper-demo#1]
It would be nice if the routing mechanism avoid routing "api" to sapper middleware, so I can write my own lambdas there. I tried to figure it out myself but I am not sure if it is polka thing or it is defined somewhere else.

**Comment by antony** [comment]
You could define alternate routes within your 'now.json' or modify the plugin to add these routes. Beyond that I'm not really sure, since my API exists outside of my Sapper project.

**Comment by vorcigernix** [comment]
Okay, solved, thanks. If anyone else needs an example how to do that, look at now.json here: https://github.com/vorcigernix/reactiveconf-sapper-workshop/tree/lambda
