### ISSUE TITLE
Now Deployment Using Custom Module

### ISSUE THREAD

**Issue by stunjiturner** [beyonk-adventures/now-sapper-demo#2]
I have a custom module in node_modules, underneath my src folder like https://github.com/sveltejs/realworld/tree/master/sr, in my case its a svelte transition in a javascript file called crossfade, but now deployment fails that it can find the custom module 'crossfade'

**Comment by antony** [comment]
@stunjiturner I think your repo was deleted, as I can't see it.

It's possible the `now-sapper` builder doesn't send modules under `src/node_modules` correctly - have you checked the deployed code bundle to see if your module is there?
