### ISSUE TITLE
Example of Express usage

### ISSUE THREAD

**Issue by donovanh** [beyonk-adventures/now-sapper-demo#3]
I've tried adjusting the example project to use Express but it doesn't seem to work. Here's the fork in which I made the adjustments:

https://github.com/donovanh/now-sapper-demo

The above runs locally but when deployed to Now fails with a "missing server.js" error (no build errors though). I'm not sure why.

Maybe I've missed something? Either way it could be good to have an example implementation if it can be made to work.

**Comment by bartveneman** [comment]
Had the same issue, try removing the engines field from your package.json, that did the trick for me.

**Comment by donovanh** [comment]
Thanks @bartveneman that does seem to help
