### ISSUE TITLE
SSR for /blog doesn't work on Zeit Now v2

### ISSUE THREAD

**Issue by tomsoderlund** [beyonk-adventures/now-sapper-demo#5]
See https://test-v2-qa.tomsoderlund.now.sh/blog

You see that `/blog` returns 500 error:

    request to http://127.0.0.1:0/blog.json failed, reason: connect ECONNREFUSED 127.0.0.1

But https://test-v2-qa.tomsoderlund.now.sh/blog.json returns valid JSON, so something with how the URL is requested?

**Comment by thgh** [comment]
Probably related: https://github.com/thgh/now-sapper#using-fetch-serverside

**Comment by tomsoderlund** [comment]
Thank you @thgh, that was it!

For anyone else with the same problem; I made this helper function:

    export default function zeitNowUrl (path, host = '') {
      const baseUrl = (!process.browser && process.env.NOW_REGION)
        ? `https://${host}`
        : ''
      return `${baseUrl}/${path}`
    }

...and then in each page:

    <script context="module">
      import zeitNowUrl from '../../lib/zeitNowUrl'

      export function preload({ host, params, query }) {
        return this.fetch(zeitNowUrl('blog.json', host)).then(r => r.json()).then(posts => {
          return { posts }
        })
      }
    </script>

**Comment by thgh** [comment]
The workaround isn't needed anymore 🎉 
Fix has been released in now-sapper v0.39.0! Thanks @fpaboim
